### PR TITLE
Week 2 Submission

### PR DESCRIPTION
**Pull request by vwinstea**
I've completed all of the content for week 2. I have a few questions about the work so far:

1. Is there any way to use flexbox to change the orientation of an element? I'm used to using floats so I was used to being able to switch the side an image is on between left and right without touching html. Is there any way to do this with flexbox?
2. For posting the ratings, I was having trouble updating the rating after posting to the API so I just updated my local list as well. Is there any way to wait for an async function such as fetch to finish before calling another function?
3. I'm completely lost on making a custom URL for each random recipe. Any hints/suggestions?

Thanks for a great 2nd Week of bootcamp!
-Vance

### CODE REVIEW

**Comment by zimeg** [comment]
Without digging into the code, I can try and answer those questions (all of which are really good)
1. I think by orientation you mean position on the screen? If so, then **yes**, although floats are probably easier if you're just dealing with single elements. With flexbox, you would create a parent element with `width: 100%` and then you could `justify-content: flex-end`, which would move the children element(s) to the right side of the parent.
2. I'm pretty sure I also manually added ratings to my list, but **there is a way** to do it with respect to the API response. You can chain `.then()` to your fetch call (assuming the API actually returns something). I'm not 100% sure if this would work for our project, but that is how you'd go about doing it.
3. I worded that custom URL requirement fairly poorly, sorry about that. I would look into URL hashes in JS. You're able to manipulate and read the URL using JS with this, which should be enough to get you going. Let me know if this is still confusing.

Sorry for the major delay on those responses 😰

**Comment by zimeg** [comment]
Overall, everything looks super clean! I love those buttons for changing serving sizes + the addition of showing total number of ratings! Keep up the great work!

And just commit the change for the custom URL once you've done it. That should go straight into this PR. Let me know if you have any questions

**Comment by vwinstea** [comment]
I just committed the changes for URL hashing and for milestone 3. Should I make a new PR for milestone 3, or should I continue to use this one?

**Comment by zimeg** [comment]
Milestone 2 **and** 3 both look really amazing! Great job on that 👍

**Pull request closed without merging**
